In [1]:
# NUMPY
# create array
from numpy import array
# create array from python data type array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [2]:
# create empty array
from numpy import empty,zeros, ones
a = empty([3,3])
print(a)

print('*'*20)

a1 = zeros([3,5])
print(a1)

print('*'*20)

a2 = ones([2,7])
print(a2)

[[6.92848625e-310 2.56478726e-316 6.92846880e-310]
 [6.92845715e-310 6.92848711e-310 6.92848711e-310]
 [6.92848708e-310 6.92848708e-310 3.95252517e-322]]
********************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
********************
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [3]:
from numpy import vstack
b1 = array([1,2,3])
b2 = array([[1,2,3],[5,6,7]])
b3 = vstack((b1,b2,[2,3,45])) # various ways of stacking, and yes dimensions matching 
print(b3)
print(b3.shape)
b3[2,1]
b4 = array([[1],[2],[3],[4]])
print("the shape of b.4 is ")
print( b4.shape) # 4 r & 1 c

[[ 1  2  3]
 [ 1  2  3]
 [ 5  6  7]
 [ 2  3 45]]
(4, 3)
the shape of b.4 is 
(4, 1)


In [4]:
from numpy import hstack
bh3 = hstack((b1,[3,4,5]))
print(bh3)
print(bh3.shape) #6 rows alone

[1 2 3 3 4 5]
(6,)


In [5]:
bh3[1]

2

In [6]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

#It is common to need to reshape two-dimensional data where each row represents a sequence
#into a three-dimensional array for algorithms that expect multiple samples of one or more time
#steps and one or more features. A good example is the LSTM recurrent neural network model
#in the Keras deep learning library

(3, 2)
(3, 2, 1)


In [7]:
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [8]:
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[1:2, :-1], data[:, -1] # rows range followed by columns range
print(X)
print(y)

[[44 55]]
[33 66 99]


Arrays with dierent sizes cannot be added, subtracted, or generally be used in arithmetic. A
way to overcome this is to duplicate the smaller array so that it has the dimensionality and
size as the larger array. This is called array broadcasting

### Broadcasting` 
#### extend an array along the last unequal dimension so that operations that require matching sizes are then possible

In [9]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [10]:
# broadcast scalar to two-dimensional array
from numpy import array
# define array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [11]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define one-dimensional array
b = array([1, 2, 3])
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [12]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define one-dimensional array
#b = array([[1], [2], [3]])
# mis match can be along m or n not both at the same time :(
b = array([[1], [2]])
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[[1]
 [2]]
[[2 3 4]
 [3 4 5]]


Arithmetic, including broadcasting, 
can only be performed when the shape of each dimension in the arrays are equal 
or one has the dimension size of 1. 
The dimensions are considered in reverse order, starting with the trailing
dimension; for example, looking at columns before rows in a two-dimensional case. [n first and then m in an m*n matrix]

In [13]:
# vector multiplication
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a * b
print(c) # actual multipllicaiton


[1 2 3]
[1 2 3]
[1 4 9]


In [14]:
c = a - b
print(c)

[0 0 0]


In [15]:
c = a + b
print(c)

[2 4 6]


In [16]:
c = a / b
print(c)

[1. 1. 1.]


In [17]:
c = a.dot(b)
print(c) # dot product

14


In [18]:
d=5.3
c = a * d
print(c)

[ 5.3 10.6 15.9]


In [19]:
##stopped at vector norms

In [20]:
# L1 norm: sum of absolute values
# L2 norm square root of sum of sqares of the vector elements
# max.. manx element of the vector

# the above are ways to calculate vector norm.. or vector magnitude.

In [21]:
# vector L2 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


In [22]:
l1 = norm(a,1) # call norm funciton with 1 as the parameter

In [23]:
print(l1)

6.0


In [25]:
from math import inf # this is required
from numpy import array
from numpy.linalg import norm

linf = norm(a,inf) # inf as in infinity... :0 go figure...
print(linf)

3.0


In [26]:
# matrix addition, subtraction nothing new
# matrix multiplicaiton.. 
# the circle product is what they refer to as Hadamard produt
# hadamard product involves direct term by term multiplicaiton of elements to forma  a new matrix

# matrix Hadamard product
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# multiply matrices
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [27]:
# matrix division.. term by term division
C = A / B
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# matrix multiplicaiton
# the actrual multiplication A(m,n).B(n,k) yeilds a matrix C(m,k)
# matrix dot product
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)
# multiply matrices
C = A.dot(B)
print('c is...')
print(C)
# multiply matrices with @ operator
D = A @ B
print('d is...')
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
c is...
[[ 7 10]
 [15 22]
 [23 34]]
d is...
[[ 7 10]
 [15 22]
 [23 34]]


In [30]:
# matrix vector multiplicaiotn
# c = A.v or even compact noatioan c = Av
# notice the lower case letters used for vectors
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


In [31]:
# try reversing.. should yeild error message
#C = B.dot(A)
#print(C)

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [33]:
#Matrix scalar multiplicaiton
b =12
A = C*b
print(A)

[18. 42. 66.]


In [ ]:
#Chap 10